### ISSUE TITLE
How to get game's lastupdate in "userGameList"?

### ISSUE THREAD

**Issue by viskem** [elminsterjimmy/PSN-API#1]
if the function:
can get the game's time of lastupdate from 'userGameList'
can get image of trophy which user not earned from 'userGameTrophyList'

then, this api will be pretty good!!!

**Comment by elminsterjimmy** [comment]
Hi viskem,
Thank you for your feedback.
Regarding to your advises, I'm working on getting the image of unearned trophy. It cannot directly retrieved from current psn json result, but could be achieved by collecting the trophy information from someone who's earned. So my approach will be collect the trophy information as much as possible and cache them in database or files.
The result of userGameList is ordered by recent played, but to get the last update timestamp of user's game list, it is not available so far. If you got any idea about it, could you shared that?

**Comment by viskem** [comment]
i see you get data from "https://my.playstation.com/playstation/psn/public/trophies/?onlineId=ViskemEvan&_=1438837460933" & "https://my.playstation.com/playstation/psn/profile/compareGames/trophies/data?gameId=NPWR06221_00&userIds=ViskemEvan" ?

can you get data from "https://{{region}}-tpy.np.community.playstation.net/trophy/v1/trophyTitles?fields=%40default&npLanguage={{lang}}&iconSize={{iconsize}}&platform=PS3%2CPSVITA%2CPS4&offset={{offset}}&limit={{limit}}&comparedUser={{id}}'" ?

``` php
trophyData:'https://{{region}}-tpy.np.community.playstation.net/trophy/v1/trophyTitles?fields=%40default&npLanguage={{lang}}&iconSize={{iconsize}}&platform=PS3%2CPSVITA%2CPS4&offset={{offset}}&limit={{limit}}&comparedUser={{id}}'   // NOTE: All server are in the US, the only change are market restrictions
trophyDataList:'https://{{region}}-tpy.np.community.playstation.net/trophy/v1/trophyTitles/{{npCommunicationId}}/trophyGroups/{{groupId}}/trophies?fields=%40default,trophyRare,trophyEarnedRate&npLanguage={{lang}}'
trophyGroupList:'https://{{region}}-tpy.np.community.playstation.net/trophy/v1/trophyTitles/{{npCommunicationId}}/trophyGroups/?npLanguage={{lang}}'
```

(from gumer-psn/psn.js)

**Comment by elminsterjimmy** [comment]
Hi viskem,
I checked the URLs you mentioned, when I call these URLs, they results a http 401 status. It seems the URLs use another authorization route than the one I used.
After checked gumer-psn/psn.js, I found that it follows the route after android app does, but the authorization part does not work anymore. I have no packet analysis tool which could work with android so far.

**Comment by elminsterjimmy** [comment]
I updated new distribution which will cache the trophy data into hsqldb. It can be used to collect the trophy infos in daemon. I think you may wanna try it out.
